name: OK

on:
  pull_request:

env:
  NODE: 12.x

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: npm install
